// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bibliotecaReclamao.Banco.Conexao;

#nullable disable

namespace bibliotecaReclamao.Migrations
{
    [DbContext(typeof(ConexaoContexto))]
    [Migration("20250610142120_migrationFOTO")]
    partial class migrationFOTO
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("bibliotecaReclamao.Banco.Modelos.Reclamacao", b =>
                {
                    b.Property<int>("IdReclamacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdReclamacao"));

                    b.Property<string>("ConteudoReclamacao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataCriacaoReclamacao")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("IdReclamacao");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Reclamacao");
                });

            modelBuilder.Entity("bibliotecaReclamao.Banco.Modelos.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("EmailUsuario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImagemUsuario")
                        .HasColumnType("longtext");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SenhaUsuario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("bibliotecaReclamao.Banco.Modelos.Reclamacao", b =>
                {
                    b.HasOne("bibliotecaReclamao.Banco.Modelos.Usuario", "UsuarioAssociado")
                        .WithMany("Reclamacoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UsuarioAssociado");
                });

            modelBuilder.Entity("bibliotecaReclamao.Banco.Modelos.Usuario", b =>
                {
                    b.Navigation("Reclamacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
